package dev.jyotiraditya.dmt.data.remote.youtube

import android.net.Uri
import android.util.Log
import androidx.annotation.OptIn
import androidx.media3.common.C
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.DataSource
import androidx.media3.datasource.DataSpec
import androidx.media3.datasource.DefaultHttpDataSource
import androidx.media3.datasource.TransferListener
import java.io.IOException
import javax.inject.Inject
import javax.inject.Singleton

private const val TAG = "YoutubeStreamDS"

/**
 * DataSource for YouTube Music streaming.
 *
 * Resolves [youtube://video/{videoId}] URIs to playable stream URLs via
 * [YoutubeStreamResolver], then delegates actual HTTP transfer to a
 * [DefaultHttpDataSource] configured with the EXACT User-Agent from
 * the Innertube context that generated the stream URL.
 *
 * IMPORTANT: The User-Agent MUST match the client context used to request
 * the stream URL. If the URL was generated by the IOS context, send the
 * iOS User-Agent. If by AndroidMusic, send the Android Music User-Agent.
 * A mismatch (e.g., desktop Firefox UA on an iOS-generated URL) causes
 * YouTube CDN to reject with HTTP 403 → ERROR_CODE_IO_BAD_HTTP_STATUS.
 */
@OptIn(UnstableApi::class)
class YoutubeStreamDataSource private constructor(
    private val resolver: YoutubeStreamResolver,
) : DataSource {

    private var inner: DataSource? = null
    private var openedUri: Uri? = null

    @Singleton
    class Factory @Inject constructor(
        private val resolver: YoutubeStreamResolver,
    ) : DataSource.Factory {
        override fun createDataSource(): DataSource {
            return YoutubeStreamDataSource(resolver)
        }
    }

    override fun addTransferListener(transferListener: TransferListener) {
        inner?.addTransferListener(transferListener)
    }

    override fun open(dataSpec: DataSpec): Long {
        val videoId = dataSpec.uri.lastPathSegment
            ?: throw IOException("No video ID in YouTube URI: ${dataSpec.uri}")

        val resolved = kotlinx.coroutines.runBlocking {
            resolver.resolve(videoId)
        } ?: throw IOException("Could not resolve YouTube stream for $videoId")

        openedUri = Uri.parse(resolved.url)
        Log.d(TAG, "Stream resolved: ${resolved.url.take(80)}")

        // Use the exact User-Agent from the Innertube context that generated the URL
        // This is CRITICAL to avoid HTTP 403 from YouTube CDN
        val httpFactory = DefaultHttpDataSource.Factory()
            .setConnectTimeoutMs(16_000)
            .setReadTimeoutMs(8_000)
            .setUserAgent(resolved.userAgent)
            .setAllowCrossProtocolRedirects(true)

        inner = httpFactory.createDataSource()

        val resolvedSpec = dataSpec.buildUpon().setUri(openedUri!!).build()
        return inner!!.open(resolvedSpec)
    }

    override fun read(target: ByteArray, offset: Int, length: Int): Int {
        val ds = inner
        if (ds == null) {
            Log.w(TAG, "read() called but inner DataSource is null")
            return C.RESULT_END_OF_INPUT
        }
        return ds.read(target, offset, length)
    }

    override fun getResponseHeaders(): Map<String, List<String>> =
        inner?.responseHeaders ?: emptyMap()

    override fun getUri(): Uri? = inner?.uri ?: openedUri

    override fun close() {
        inner?.close()
        inner = null
        openedUri = null
    }
}
